apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: dockerapp
        imagePullPolicy: Never
        ports:
        - containerPort: 5000